### ISSUE TITLE
Teemojen monistaminen

### ISSUE THREAD

**Issue by SeveriLybeck** [Project-OtaWilma/OtaWilma-frontend#3]
##Otawilman teemoja tulisi pystyä monistamaan

Teemojen nurkkaan voisi lisätä esim. kuvan mukaisen monistusnäppäimen, jolla saisi aloitettua uuden custom teeman teon vanhan pohjalta. Tällöin esim. oman dark themen teko otawilmaan olisi helpompaa.
![kuva](https://user-images.githubusercontent.com/35189459/186888394-ac44ef24-5371-4a42-af62-c1d2eea8b23d.png)

**Comment by TuuKeZu** [comment]
Teemojen luonnin yhteydessä kysytään nykyään haluatko luoda vaalean vai tumman teeman. Teemojen "monistaminen" jää toistaiseksi ominaisuudeksi, joka saatetaan lisätä tulevaisuudessa.
