### ISSUE TITLE
Kehittäjän taito pula

### ISSUE THREAD

**Issue by villevilli** [Project-OtaWilma/OtaWilma-frontend#4]
Aloin tutkailla verkkosivun lähdekoodia ja tietämättömyydessäni ajattelin lähteä miettimään korjausta ongelmaan #2. Avasin views kansion. Kansion sisällä avasin messages.html tiedoston. Kauheudekseni näin että navigaatio baari on erikseen tiedostossa ja copy pastettu kaikkialle.

```html
<div class="top" id="top">
            <div class="user-info">
                <div class="user-data">
                    <h1 id="username"></h1>
                    <h2>Opiskelija</h2>
                    <div class="logout" id="logout">
                        <h6>Kirjaudu ulos</h6>
                    </div>
                </div>
            </div>
            <button id="/views/frontpage.html">
                <h1 class="logo-text">OtaWilma</h1>
            </button>
            <button id="/views/messages.html">
                <h5>Viestit</h5>
            </button>
            <button id="/views/grades.html">
                <h5>Opinnot</h5>
            </button>
            <button id="/views/course-tray.html">
                <h5>Kurssitarjotin</h5>
            </button>
            <button id="/views/news.html">
                <h5>Tiedotteet</h5>
            </button>
            <button id="/views/teachers.html">
                <h5>Opettajat</h5>
            </button>
            <button id="/views/settings.html">
                <h5>Asetukset</h5>
            </button>
        </div>
```

# **Tämä toistuu lähes _jokaisessa_ sivussa.­­**
Mielestäni kehittäjä voisi opetella käyttämään jotain frontend kehitykseen suuniteltua työkalua.
Koodissa on myös lisää toistuvia osia mutta en uskalla niitä lähteä edes ajattelemaan.

<sup>Vaadin myös korvauksia tämän koodin aiheuttamista henkisistä traumoista</sup>

**Comment by TuuKeZu** [comment]
tämän issuen korjaamiseen ei todellakaan mennyt 40h reactin opiskelua

**Comment by TuuKeZu** [comment]
#### korvauksia koodin laadusta ei ole kuitenkaan saatavilla
