### ISSUE TITLE
Etusivun lukujärjestyksen rivitys

### ISSUE THREAD

**Issue by SeveriLybeck** [Project-OtaWilma/OtaWilma-frontend#6]
Etusivun lukujärjestyksessä liian pitkät opettajan nimi + opintojakson nimi + luokka yhdistelmät tulevat lukujärjestyksen laatikoiden yli.
![kuva](https://user-images.githubusercontent.com/35189459/187133498-71b9efb6-43ad-4b10-a949-4eba281ba8cb.png)

Ehdotan kuvan mukaista vaihtoehtosta rivitystä, jossa opintojakson nimi ja luokka ovat samalla rivillä, joiden alla on merkitty opettaja:
![kuva](https://user-images.githubusercontent.com/35189459/187133784-a528735c-500a-45f6-8e66-8a144c8fff41.png)

**Comment by TuuKeZu** [comment]
Korjattu betan viimeisimmässä buildissa
![image](https://user-images.githubusercontent.com/72083030/204885938-8143b91e-e9b7-4795-b2a1-5cdcaf34670d.png)
